apiVersion: v1
data:
  init-db.sql: |
    CREATE DATABASE IF NOT EXISTS wordpress;
    GRANT ALL PRIVILEGES ON wordpress.* TO 'root'@'%';
    FLUSH PRIVILEGES;
kind: ConfigMap
metadata:
  name: mysql-init-db
